# Generated by Django 4.1.1 on 2023-01-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(null=True)),
                ("Status", models.IntegerField(default=1)),
                ("AddedBy", models.IntegerField(default=0)),
                ("Ip", models.GenericIPAddressField(null=True)),
                ("Edited_Date", models.DateTimeField(auto_now_add=True)),
                ("EditedBy", models.IntegerField(default=0)),
                ("EditedIp", models.GenericIPAddressField(null=True)),
                ("Name", models.CharField(max_length=50)),
                ("Reference", models.CharField(max_length=20)),
                ("Products", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(null=True)),
                ("Status", models.IntegerField(default=1)),
                ("AddedBy", models.IntegerField(default=0)),
                ("Ip", models.GenericIPAddressField(null=True)),
                ("Edited_Date", models.DateTimeField(auto_now_add=True)),
                ("EditedBy", models.IntegerField(default=0)),
                ("EditedIp", models.GenericIPAddressField(null=True)),
                ("Name", models.CharField(max_length=50)),
                ("Price", models.FloatField()),
                ("Reference", models.CharField(max_length=20)),
                (
                    "Category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrator.category",
                    ),
                ),
            ],
        ),
    ]
