# Generated by Django 4.1.1 on 2023-01-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="Reference",
            field=models.CharField(max_length=20),
        ),
    ]
