# Generated by Django 4.1.1 on 2023-01-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(null=True)),
                ("Status", models.IntegerField(default=1)),
                ("AddedBy", models.IntegerField(default=0)),
                ("Ip", models.GenericIPAddressField(null=True)),
                ("Edited_Date", models.DateTimeField(auto_now_add=True)),
                ("EditedBy", models.IntegerField(default=0)),
                ("EditedIp", models.GenericIPAddressField(null=True)),
                ("Reference", models.CharField(max_length=20)),
                ("Company", models.CharField(max_length=50)),
                ("Address", models.CharField(max_length=250)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(max_length=15)),
                ("ECDate", models.DateField()),
                ("ESValue", models.FloatField()),
            ],
        ),
    ]
