# Generated by Django 4.1.1 on 2023-01-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0002_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="State",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
