# Generated by Django 4.1.1 on 2023-01-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0004_lead_cmail_lead_cname_lead_cnumber_lead_salesman"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="ECDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
