# Generated by Django 4.1.1 on 2023-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0005_alter_lead_ecdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="Lead_Status",
            field=models.IntegerField(default=0),
        ),
    ]
