# Generated by Django 4.1.1 on 2023-01-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0006_lead_lead_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead_Update",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField()),
                ("AddedBy", models.IntegerField(default=0)),
                ("Ip", models.GenericIPAddressField(blank=True, null=True)),
                ("Description", models.TextField()),
                (
                    "Lead",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="administrator.lead",
                    ),
                ),
            ],
        ),
    ]
