# Generated by Django 4.1.1 on 2023-01-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0008_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead_update",
            name="Status",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Lead_Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField()),
                ("Status", models.IntegerField(default=1)),
                ("AddedBy", models.IntegerField(default=0)),
                ("Ip", models.GenericIPAddressField(blank=True, null=True)),
                ("Mode", models.CharField(max_length=25)),
                ("From", models.TimeField()),
                ("To", models.TimeField()),
                ("Description", models.TextField()),
                (
                    "Lead",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="administrator.lead",
                    ),
                ),
            ],
        ),
    ]
