# Generated by Django 4.1.1 on 2023-01-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0009_lead_update_status_lead_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachments",
            name="Name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
