# Generated by Django 4.1.1 on 2023-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0010_attachments_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead_schedule",
            name="AddedDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="lead_update",
            name="AddedDate",
            field=models.DateField(null=True),
        ),
    ]
