# Generated by Django 4.1.1 on 2023-01-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0011_lead_schedule_addeddate_lead_update_addeddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="To_Client",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="To_Opertunity",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="To_Project",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="To_Proposal",
            field=models.DateField(null=True),
        ),
    ]
