# Generated by Django 4.1.1 on 2023-01-30 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrator",
            "0012_lead_to_client_lead_to_opertunity_lead_to_project_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField()),
                ("Status", models.IntegerField(default=1)),
                ("AddedBy", models.IntegerField(default=0)),
                ("Ip", models.GenericIPAddressField(blank=True, null=True)),
                ("Scope", models.TextField()),
                ("Payment", models.TextField()),
                ("Exclusion", models.TextField()),
                ("Terms_Condition", models.TextField()),
                ("Oppertunity", models.TextField()),
                (
                    "Lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrator.lead",
                    ),
                ),
                ("Products", models.ManyToManyField(to="administrator.product")),
            ],
        ),
    ]
