# Generated by Django 4.1.1 on 2023-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0013_proposal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachments",
            name="Lead_Update",
        ),
        migrations.AddField(
            model_name="lead_update",
            name="Attachments",
            field=models.ManyToManyField(to="administrator.attachments"),
        ),
    ]
