# Generated by Django 4.1.1 on 2023-01-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0014_remove_attachments_lead_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead_update",
            name="Attachments",
            field=models.ManyToManyField(null=True, to="administrator.attachments"),
        ),
    ]
