# Generated by Django 4.1.1 on 2023-01-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0015_alter_lead_update_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead_schedule",
            name="Schedule_Status",
            field=models.IntegerField(default=1),
        ),
    ]
