# Generated by Django 4.1.1 on 2023-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0017_lead_schedule_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead_schedule",
            name="Attachment",
            field=models.ManyToManyField(null=True, to="administrator.attachments"),
        ),
        migrations.AddField(
            model_name="lead_schedule",
            name="Update_Date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="lead_schedule",
            name="Update_Description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
