# Generated by Django 4.1.1 on 2023-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrator",
            "0018_lead_schedule_attachment_lead_schedule_update_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead_schedule",
            name="Attachment",
            field=models.ManyToManyField(to="administrator.attachments"),
        ),
        migrations.AlterField(
            model_name="lead_update",
            name="Attachments",
            field=models.ManyToManyField(to="administrator.attachments"),
        ),
    ]
