# Generated by Django 4.1.1 on 2023-01-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0020_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="Task_Status",
            field=models.IntegerField(default=0),
        ),
    ]
