# Generated by Django 4.1.1 on 2023-01-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0021_task_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="Completed_Date",
            field=models.DateField(null=True),
        ),
    ]
