# Generated by Django 4.1.1 on 2023-01-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0022_task_completed_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="Exclusion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="Oppertunity",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="Payment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="Scope",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="Terms_Condition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
