# Generated by Django 4.1.1 on 2023-01-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "administrator",
            "0023_alter_proposal_exclusion_alter_proposal_oppertunity_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Replays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField()),
                ("Status", models.IntegerField(default=1)),
                ("AddedBy", models.IntegerField(default=0)),
                ("Ip", models.GenericIPAddressField(blank=True, null=True)),
                ("Message", models.TextField()),
                (
                    "Task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrator.task",
                    ),
                ),
            ],
        ),
    ]
