# Generated by Django 4.1.1 on 2023-02-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0024_replays"),
    ]

    operations = [
        migrations.AddField(
            model_name="replays",
            name="Attachments",
            field=models.ManyToManyField(to="administrator.attachments"),
        ),
    ]
