# Generated by Django 4.1.1 on 2023-02-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0025_replays_attachments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="Descrition",
            new_name="Description",
        ),
    ]
