# Generated by Django 4.1.1 on 2023-02-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0026_rename_descrition_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="replays",
            name="AddedDate",
            field=models.DateField(null=True),
        ),
    ]
