# Generated by Django 4.1.1 on 2023-02-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0027_replays_addeddate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AddedDate", models.DateField(null=True)),
                ("Message", models.TextField()),
                ("Attachments", models.ManyToManyField(to="administrator.attachments")),
                (
                    "Task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrator.task",
                    ),
                ),
            ],
        ),
    ]
