# Generated by Django 4.1.1 on 2023-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0029_salesman_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesman_report",
            name="Completed_Tasks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Pending_Tasks",
            field=models.IntegerField(default=0),
        ),
    ]
