# Generated by Django 4.1.1 on 2023-02-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0030_salesman_report_completed_tasks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="Priority",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
