# Generated by Django 4.1.1 on 2023-02-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0031_alter_task_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachments",
            name="Name",
        ),
    ]
