# Generated by Django 4.1.1 on 2023-02-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0032_remove_attachments_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachments",
            name="Name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
