# Generated by Django 4.1.1 on 2023-02-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0033_attachments_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachments",
            name="Format",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
