# Generated by Django 4.1.1 on 2023-02-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0035_remove_salesman_report_completed_tasks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesman_report",
            name="Opportunities",
        ),
        migrations.RemoveField(
            model_name="salesman_report",
            name="Proposals",
        ),
    ]
