# Generated by Django 4.1.1 on 2023-02-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0036_remove_salesman_report_opportunities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesman_report",
            name="Leads",
        ),
        migrations.RemoveField(
            model_name="salesman_report",
            name="Tasks",
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Completed_Tasks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Lead_Faild",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Lead_Succes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Lead_Total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Opportunity_Faild",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Opportunity_Success",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Opportunity_Total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Pending_Tasks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Previous_Meetings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Proposal_Faild",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Proposal_Success",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Proposal_Total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="SV_Failed",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="SV_Success",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="SV_Total",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="salesman_report",
            name="Upcoming_Meetings",
            field=models.IntegerField(default=0),
        ),
    ]
