# Generated by Django 4.1.1 on 2023-02-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0037_remove_salesman_report_leads_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesman_report",
            name="Status",
            field=models.IntegerField(default=1),
        ),
    ]
