# Generated by Django 4.1.1 on 2023-02-04 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0038_salesman_report_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesman_report",
            old_name="SV_Total",
            new_name="SV_Pending",
        ),
    ]
