# Generated by Django 4.1.1 on 2023-02-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0039_rename_sv_total_salesman_report_sv_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="Previous_Meetings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="Upcoming_Meetings",
            field=models.IntegerField(default=0),
        ),
    ]
