# Generated by Django 4.1.1 on 2023-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0040_lead_previous_meetings_lead_upcoming_meetings"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="Reject_Date",
            field=models.DateField(null=True),
        ),
    ]
