# Generated by Django 4.1.1 on 2023-02-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0041_lead_reject_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="Cancel_Date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="Cancel_Reason",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
