# Generated by Django 4.1.1 on 2023-02-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0043_alter_lead_cancel_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Price",
            new_name="Buying_Price",
        ),
        migrations.AddField(
            model_name="product",
            name="Selling_Price",
            field=models.FloatField(null=True),
        ),
    ]
