# Generated by Django 4.1.1 on 2023-02-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0044_rename_price_product_buying_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Description",
            field=models.TextField(null=True),
        ),
    ]
