# Generated by Django 4.1.1 on 2023-02-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0046_remove_proposal_products_proposal_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Selling_Price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
