# Generated by Django 4.1.1 on 2023-02-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0047_alter_product_selling_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal_items",
            name="Sell_Price",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
