# Generated by Django 4.1.1 on 2023-02-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0048_proposal_items_sell_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="Reference",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
