# Generated by Django 4.1.1 on 2023-02-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0049_proposal_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="Proposal_Status",
            field=models.IntegerField(default=10),
        ),
    ]
