# Generated by Django 4.1.1 on 2023-02-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0051_sales_target"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales_target",
            name="From",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sales_target",
            name="Targets",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="sales_target",
            name="To",
            field=models.DateField(blank=True, null=True),
        ),
    ]
