# Generated by Django 4.1.1 on 2023-02-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0052_sales_target_from_sales_target_targets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="Accepted_proposals",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="Rejected_Proposals",
            field=models.IntegerField(default=0),
        ),
    ]
