# Generated by Django 4.1.1 on 2023-02-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0055_proposal_attachments_proposal_po_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales_target",
            name="Archived",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="sales_target",
            name="Balance",
            field=models.FloatField(default=0),
        ),
    ]
