# Generated by Django 4.1.1 on 2023-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0056_sales_target_archived_sales_target_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="Grand_Total",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
