# Generated by Django 4.1.1 on 2023-02-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0058_alter_proposal_grand_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales_target",
            name="Failed",
            field=models.FloatField(default=0),
        ),
    ]
