# Generated by Django 4.1.1 on 2023-02-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0059_sales_target_failed"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales_target",
            name="Pending",
            field=models.FloatField(default=0),
        ),
    ]
