# Generated by Django 4.1.1 on 2023-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0060_sales_target_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="PO_Description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="PO_Value",
            field=models.CharField(max_length=225, null=True),
        ),
    ]
