# Generated by Django 4.1.1 on 2023-02-24 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0061_proposal_po_description_proposal_po_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField()),
                ("Status", models.IntegerField(default=1)),
                ("AddedBy", models.IntegerField(default=0)),
                ("Ip", models.GenericIPAddressField(blank=True, null=True)),
                ("Reference", models.CharField(max_length=25)),
                ("Amount", models.FloatField()),
                (
                    "Proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrator.proposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField()),
                ("Status", models.IntegerField(default=1)),
                ("AddedBy", models.IntegerField(default=0)),
                ("Ip", models.GenericIPAddressField(blank=True, null=True)),
                ("Reference", models.CharField(max_length=25)),
                ("Amount", models.FloatField()),
                (
                    "Proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrator.proposal",
                    ),
                ),
            ],
        ),
    ]
