# Generated by Django 4.1.1 on 2023-02-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0064_proposal_action_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="PO_Value",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
