# Generated by Django 4.1.1 on 2023-02-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0065_alter_proposal_po_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="PO_Value",
            field=models.FloatField(null=True),
        ),
    ]
