# Generated by Django 4.1.1 on 2023-02-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrator", "0066_alter_proposal_po_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead_schedule",
            name="notification",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="notification",
            field=models.IntegerField(default=1),
        ),
    ]
